
const ddata={
  phrasalVerbs:{
    name:"phrasalVerbs",
    picture404:"https://media.licdn.com/dms/image/C4D22AQHxvvQ2jTQl2g/feedshare-shrink_800/0/1679041539177?e=2147483647&v=beta&t=CzIaU5BTjL7pa4c2Um4Fvt1Y3S7Apl2y2ikNJC1Iqx8",
    contents:[
      {name:"cut down on",description:["reduce"]},
      {name:"fall apart",description:["fail to succeed","break up", "feel awful"],synonyms:["break off"]},
      {name:"do without",description:["get by"]},
      {name:"feel for",description:["symphasize"]},
      {name:"drop in",description:["go to someone without  appointment"]},
      {name: "fall out",description:["to fall out of something","to argue with someone without result", "devastate"]},
      {name:"figure out",description:["discover"],synonyms:["work out"]},
      {name:"get round",description:["to do something that you have intended to do for a long time (with to)","to recover (without to)","deceive somebody (with object)","persuade someone using charm (with object)","deal successfully with problem","travel around"],synonyms:["get about"]},
      {name:"take after",description:["to resemble somebody"]},
      {name:"let down",description:["to dissapoint someone","lengthen a garment (smth)"],synonyms:["take down"]},
      {name:"hand down",description:["pass something on to a younger person or a successor","announce something, especially a judgement or sentence, formally or publicly"]},
      {name:"break down",description:["stop working","mental ___"],synonyms:["go down"]},
      {name:"fall through",description:["fail to happen"]},
      {name:"look back on",description:["nostalgia"]},
      {name:"look out for",description:["to be sure that a person doesnt get hurt"]},
      {name:"look after",description:["take care of somebody"]},
      {name:"look to",description:["expect that someone will provide something that you want (+ object)"]},
      {name:"come into",description:["inherit something"]},
      {name:"come up with",description:["think or suggest smth"]},
      {name:"go over",description:["examine or discuss in detail"]},
      {name:"go with",description:["match"]},
      {name:"look up on",description:["respect someone"]},
      {name:"look down on",description:["despise"]},
      {name:"go down",description:["to move down to a lower level or place","to reach or go as far as","BE REDUCED","to be remembered or recorded in a particular way","BE RECEIVED","to lose or be defeated","to be put in prison","stop working","happen(about crime)"],synonyms:["break down"]},
      {name:"put off",description:["postpone"],synonyms:["carry over"]},
      {name:"get together",description:["gather with others"]},
      {name:"put up with",description:["tolerate"]},
      {name:"bring about",description:["to make something happen"]},
      {name:"draw on",description:["to use inf or knowledge"]},
      {name:"flare up",description:["when violece/pain/infection gets worse"]},
      {name:"put in for",description:["make official request to do smth"]},
      {name:"fall into",description:["to start doing smth without intending to do it","to be devided in parts","to go to some state"]},
      {name:"put up to",description:["to encourage someone to do smth wrong(object in the middle)"]},
      {name:"go in for",description:["enjoy smth","compete","study something(for law example)"]},
      {name:"drift off",description:["to gradually start to sleep","to go own world"]},
      {name:"put through",description:["make someone experince smth bad(object in the middle)","to pay for someone to study at school, etc.(object in the middle)","connect a person using a phone to another person(object in the middle)"]},
      {name:"bring in",description:["introduce law,product","make money","to ask someone do a particular work(with object in the middle)"]},
      {name:"pull in",description:["move in that direction and stop there(about vehicle)","attract (for example clients)"]},
      {name:"come off",description:["to happen as planned","to be suscessful without expectation","stop using particular medicine","give a particular impression"]},
      {name:"make up for",description:["to compensate smth damaged,lost with smth good"]},
      {name:"go for",description:["choose smth","try to achieve","sell for particular ammount of money","try to hurt physicly"]},
      {name:"get off",description:["disembark","avoid punishment"],synonyms:["get away with"]},
      {name:"set off",description:["cause a series of events","to cause a loud noise/explosion(bomb/alarm)","start a journey"],synonyms:["set out","trigger off"]},
      {name:"see off",description:["to say goodbuy to person who is leaving(object in the middle)"]},
      {name:"stop off",description:["to visit some place for a short time during journey"]},
      {name:"take off",description:["undress","launch","spend time off work"]},
      {name:"carry out",description:["complete something that you have been told or said you would do","do a task"]},
      {name:'catch on',description:["become popular"]},
      {name:"call for",description:["need/require"]},
      {name:"fall back on",description:["to use something for help because no other choice is available"]},
      {name:"get out of",description:["avoid smth(with an excuse)","stop habit","leave something"],synonyms:["get away from"]},
      {name:"keep at",description:["persist with something","try to do smth better(with effort)"]},
      {name:"pull off",description:["to drive off road","to succeed in doing or achieving something difficult"],synonyms:["carry off"]},
      {name:"call off",description:["cancel an event","order something to stop attacking"]},
      {name:"pony up",description:["spend money"]},
      {name:"pull down",description:["destroy a building"," when illness or a difficult situation or experience makes you feel unhappy or physically weak"]},
      {name:"come on",description:["to start to happen or work","when illness/mood is developing gradually","said to encourage someone to do something, especially to hurry or try harder, or to tell you something","If a woman __, her period (= the blood coming from the womb that happens every month) starts","said to encourage someone to do something, especially to hurry or try harder, or to tell you something","(of an actor) to walk onto the stage"]},
      {name:"live up to",description:["to be as good as something","to achieve what is expected, esp. high standards"]},
      {name:"put on",description:["to make a device operate, or to cause a device to play something(object in the middle), such as a CD or DVD, by pressing a switch(object in the middle)","to cover part of the body with clothes, shoes, make-up, or something similar(object in the middle)","pretend","to produce or provide something, especially for the good of other people or for a special purpose","If people or animals __ weight __, they become heavier(object in the middle)","to try to persuade someone that something is true when it is not, usually as a joke(object in the middle)","to tell someone to start taking a particular medicine or eating particular foods"],synonyms:["turn out","bring out"]},
      {name:"be cut out for",description:["be the right type of person for something"]},
      {name:"turn down",description:["to refuse an offer or request(object in the middle)","if the economy or market ____, there is less business activity and fewer opportunities to make money"]},
      {name:"clear up",description:["to make a place tidy by removing things from it or putting them where they should be","If an illness ___, or if medicine __ an illness __, the illness goes away(object in the middle)","to give or find an explanation for something",]},
      {name:"get through",description:["to succeed in talking to someone on the phone","to succeed in an exam or competition","to finish something","to use up something","to deal with a difficult or unpleasant experience, or to help someone do this(object in the middle)","to succeed in persuading a legislature or other group to accept new laws (object in the middle)","to be understood or believed, or to cause someone to understand or believe you(+ to somebody object in the middle)"],synonyms:["see through"]},
      {name:"leave on",description:["To continue wearing something, especially an article of clothing"," To have something remain on someone or something else; to not take something off of someone or something else"," To keep something operational or switched to an on position; to not turn something off."]},
      {name:"look into",description:["investigate"]},
      {name:"look over",description:["to quickly examine something"],synonyms:["look through","run through"]},
      {name:"watch over",description:["care for somebody because it is your responsibility"]},
      {name:"hold up",description:["to remain strong or successful","to delay someone or something","to steal from someone using violence or the threat of violence"]},
      {name:"hold on to",description:["to keep something or someone that is important or useful"]},
      {name:"keep back",description:["to not go near something, or to prevent someone or something from going past a particular place","to not use the whole amount of something so that there is a small amount remaining for later","to not tell someone everything you know about a situation or an event that has happened"],synonyms:["hold back","set back"]},
      {name:"keep off",description:["to not go onto an area, or to stop someone or something going onto an area Don't step on [object].","to stop something touching or harming someone or something Don't step on [object].","to not eat, drink, or use something that can harm you, or to stop someone else from doing this"]},
      {name:"keep out",description:["to not go in a place, or to stop someone or something from going into a place Do not go into [area/location/building]."]},
      {name:"carry away",description:["to cause someone to become very excited and to lose control"]},
      {name:"wear out",description:["to make someone extremely tired","to use something so much that it is damaged and cannot be used any more, or to become damaged in this way"]},
      {name:"work out",description:["To do mental work in order to solve a problem","do a physical exercise"],synonyms:["figure out"]},
      {name:"let off",description:["to not punish someone who has done something wrong, or to not punish them severely(object in the middle)"]},
      {name:"take in",description:["UNDERSTAND","to go to see a film, visit an interesting building, etc for enjoyment","deceive","to receive money from sales or as payment for entrance to an event","to include something","to make a piece of clothing narrower, by changing the position of some of the stitches joining it together","to do paid work for other people, such as washing or sewing, in your home","to take care of someone and provide a place in your home for them"]},
      {name:"get back at",description:["take ravenge"]},
      {name:"see through",description:["to realize that someone is trying to deceive you to get an advantage","to continue doing a job or activity until it is finished, especially when it is difficult","to help or support someone during a difficult period in their life"],synonyms:["get through","keep on","go on","carry on"]},
      {name:"put away",description:["to put something in the place or container where it is usually kept","to eat a large amount of food:informal","to move someone into a place where people live and are cared for together, such as a mental hospital or old people's home-informal","send to prison-slang"]},
      {name:"put up",description:["to raise something, or to fix something in a raised position","to build something object in the middle","to increase the price or value of something","to provide or lend an amount of money for a particular purpose","to preserve food in glass or metal containers","to show or express a particular type of opposition to something","to suggest an idea","to make a person available","to be considered","to provide someone with a place to stay temporarily","to stay somewhere for the night","to show or express your feelings about something (negative ones)"],synonyms:["bring forward","put forward"]},
      {name:"bounce off",description:["to tell someone about an idea to find out what they think of it"]},
      {name:"bring out",description:["to make shy person more confident","to produce smth for public","to make detail noticable"],synonyms:["turn out","put on"]},
      {name:"set in",description:["smth unpleasant begins / seems likely to continue"]},
      {name:"talk through",description:["to discuss the details of smth before making decision"]},
      {name:"rough out",description:["to outline main parts without going into details"]},
      {name:"thrash out",description:["to discuss a problem in detail untill reaching agreement/finding solution"]},
      {name:"hit on",description:["have a good idea esp that tolves a problem"]},
      {name:"bring on",description:["to help someone to improve, especially through training or practice","to bring a player onto the field to play during a game","to make something happen, usually something bad"]},
      {name:"get across",description:["to make someone understnd/believe"]},
      {name:"back down",description:["admit that you were wrong"],synonyms:["take back"]},
      {name:"make for",description:["to move towards something"]},
      {name:"make out",description:["to deal with a situation, usually in a successful way"," to kiss and touch someone in a sexual way","to say something that is not true","manage to understand","try to give a specified impression; pretend","draw up or write out a list or document","manage with some difficulty to see or hear someone or something"],synonyms:["put on"]},
      {name:"make into",description:["to change something into something else"]},
      {name:"make off with",description:["steal and run away"]},
      {name:"make up with",description:["become friends again"]},
      {name:"make up",description:["to invent something, such as an excuse or a story, often in order to deceive","to prepare or arrange something by putting different things together","to make an amount of something complete or correct"]},
      {name:"do away with",description:["get rid of"]},
      {name:"pass down",description:["pass from one generation to the next"],synonyms:["hand down"]},
      {name:"fill in",description:["to give someone extra or missing information object in the middle","to do someone else's work for them because they cannot or will not do it themselves or to do it temporily","to write or type information on a document in spaces that are provided for it"],synonyms:["stand in for"]},
      {name:"fill up",description:["make something full"]},
      {name:"leave out of",description:["to exclude something"]},
      {name:"leave off",description:["to not include something or someone on a list object in the middle","to stop doing something","used to tell someone to stop being annoying  "]},
      {name:"break in",description:["force entry to a building","interrupt something, especially a conversation.","wear something, typically a pair of new shoes, until it becomes supple and comfortable.","accustom a horse to a saddle and bridle, and to being ridden.","familiarize someone with a new job or situation."],synonyms:["break into"]},
      {name:"take up",description:["to fill an amount of space or time","to fill an amount of space or time","to discuss something or deal with something"]},
      {name:"give out",description:["destribute","to complain about something","to make a piece of information public, especially information that is not true","when a machine or part of your body stops working","to last no longer, or to work no longer"],synonyms:["go down","break down"]},
      {name:"bring back",description:["recall","reintroduce"]},
      {name:"bring down",description:["reduce prices","cause to fall"]},
      {name:"bring forward",description:["suggest an indea"],synonyms:["put up","put forward"]},
      {name:"bring round",description:["help sb regain consciousness","persuade sb someone change opinion"],synonyms:["bring to"]},
      {name:"bring to",description:["persuade sb change opinion"],synonyms:["bring round"]},
      {name:"bring up",description:["raise a child","mention","introduce a subject","vomit"],synonyms:["throw up"]},
      {name:"carry off",description:["do smth succesfully"],synonyms:["pull off"]},
      {name:"carry on",description:["continue do smth despite difficulties"],synonyms:["go on","see through","keep on"]},
      {name:"carry over",description:["postpone"],synonyms:["put off"]},
      {name:"carry through",description:["complete smth despite difficulties","to help someone be able to deal with a difficult situation"],synonyms:["see through","get through"]},
      {name:"come across",description:["meet by chance"],synonyms:["run into","run across"]},
      {name:"come by",description:["obtain"]},
      {name:"come down with",description:["become ill from"],synonyms:["go down with"]},
      {name:"break into",description:["enter by force","burst into song,laugter etc"],synonyms:["break in"]},
      {name:"break off",description:["stop working temporarily","end a relationship"],synonyms:["fall apart"]},
      {name:"break out",description:["begin suddenly (war, disease, fire etc","escape from a place"],synonyms:["flare up"]},
      {name:"come out",description:["be published","bloom"]},
      {name:"come round",description:["visit casually","regain consciousness","(to + O) be persuaded to change opinion"]},
      {name:"come to",description:["regain consciousness"],synonyms:["come round"]},
      {name:"come through",description:["survive","when piece of information or a document __, you receive it","If an emotion ___, other people can notice it","to succeed in a difficult situation","to continue to live after an accident or a difficult or dangerous situation","to do something that you have agreed to do or been asked to do"],synonyms:["get through","carry out","pull off"]},
      {name:"do down",description:["speak badly of smb"],synonyms:["put down","run down"]},
      {name:"do in",description:["kill"]},
      {name:"do out",description:["clean"]},
      {name:"do up",description:["redecorate","fasten/tie"]},
      {name:"do with",description:["want","have a connection with"]},
      {name:"fall back",description:["retreat"]},
      {name:"fall for",description:["be tricked","fall in love with sb"]},
      {name:"fall in with",description:["accept sb s plans, ideas"]},
      {name:"fall off",description:["decrease"],synonyms:["bring down"]},
      {name:"fall on",description:["attack","eat food hungrily"],synonyms:["set on","set about"]},
      {name:"get about",description:["move about","spread"],synonyms:["get round"]},
      {name:"get at",description:["reach","to criticize a person repeatedly","When someone is ___ something, they mean it or are trying to express it","to influence a person illegally, usually by offering them money or threatening them","to suggest or express something in a way that is not direct or clear"]},
      {name:"get away from",description:["escape","leave"],synonyms:["get out of"]},
      {name:"get away with",description:["avoid being punished for sth"],synonyms:["get off"]},
      {name:"get down",description:["to make someone feel unhappy (object in the middle)"],},
      {name:"give away",description:["give sth for free","reveal"],synonyms:["let on"]},
      {name:"give off",description:["to produce heat, light, a smell, or a gas"]},
      {name:"go back on",description:["break the promise"]},
      {name:"go down with",description:["become ill"],synonyms:["come down with"]},
      {name:"go out",description:["be extinguished","mix socially"]},
      {name:"go round",description:["be enough for everyone to have a share"]},
      {name:"hold back",description:["to stop someone or something developing or doing as well as they should","If you __ someone or something __, you stop him, her, or it from coming or moving forward","to keep information secret from someone deliberately","to stop yourself showing an emotion"],synonyms:["keep back","keep down","set down"]},
      {name:"hold out",description:["endure","last"]},
      {name:"keep away",description:["stay away from smth"]},
      {name:"keep down",description:["to prevent a person or group of people from having any power or freedom object in the middle","to control the size or number of something and prevent it from increasing","to be able to eat or drink something without vomiting:"],synonyms:["hold back","keep back","set back"]},
      {name:"keep from",description:["prevent from (oneself in the middle)","avoid (oneself in the middle)"]},
      {name:"keep in with",description:["remain friendly with"]},
      {name:"let on",description:["reveal a secret"],synonyms:["give away"]},
      {name:"let out",description:["make (a garment) loser, larger etc"]},
      {name:"let up",description:["lessen","stop gradually"]},
      {name:"turn over",description:["If an engine ___ ____, its parts move in order to make the engine start running:","to change to a different television station","If a business __ __ a particular amount of money, it does that amount of business during a stated period","to use or allow something to be used for a different purpose","to think about something for a period of time","to give something or someone that you control to someone else","to sell and replace goods at a particular rate:"]},
      {name:"set about",description:["to attack someone","to start to do or deal with something"],synonyms:["fall on"]},
      {name:"cut back",description:["to spend less, do less, or use less of something","to cut off parts of a tree or other plant so that it becomes smaller"]},
      {name:"get on with",description:["continue after interruption"]},
      {name:"look through",description:["to read something quickly"],synonyms:["look over","run through"]},
      {name:"put aside",description:["save money"]},
      {name:"put down",description:["suppress by force","write down","attribute to","critisize"],synonyms:["do down","run down","take down"]},
      {name:"put forward",description:["propose"],synonyms:["bring forward","put up"]},
      {name:"put out",description:["entinguish","cause inconvenience"]},
      {name:"mix with",description:["socialize"]},
      {name:"mix up",description:["confuse"]},
      {name:"run into",description:["meet unepectantly"],synonyms:["come across","run across"]},
      {name:"try out",description:["test"]},
      {name:"bring along",description:["take with you"]},
      {name:"hand in",description:["give smth to somebody in charge"] },
      {name:"run across",description:["meet or find by chance"],synonyms:["come across","run into"]},
      {name:"run away with",description:["steal"]},
      {name:"run down",description:["(of a battery) lose power","(passive) be exhausted"," knock down","speak badly of sb"],synonyms:["do down","put down"]},
      {name:"run into",description:["meet by chance","collide with"],synonyms:["come across","run across"]},
      {name:"run out of",description:["come to an end"]},
      {name:"run over",description:["read through quickly"]},
      {name:"run up against",description:["face/ encounter"]},
      {name:"run through",description:["examine quickly"],synonyms:["look through","look over"]},
      {name:"see about",description:["deal with","make arrangements for"]},
      {name:"see out",description:["accompany sb to the door/exit of a house/building object in the middle"]},
      {name:"see over",description:["inspect (a house, flat etc)"]},
      {name:"set aside",description:["save for a special purpose"]},
      {name:"set back",description:["delay progress of sth","elay an event till a later date"],synonyms:["hold back","keep back","keep down"]},
      {name:"set out",description:["begin a journey","start a course of action with a clear aim in mind"],synonyms:["set off"]},
      {name:"set on",description:["(cause to) attack"],synonyms:["fall on","set about"]},
      {name:"stand by",description:["remain loyal esp in a difficult situation","watch passively","be ready for action"]},
      {name:"stand for",description:["represent","(used in questions and negations) tolerate; put up with"]},
      {name:"stand in for",description:["replace sb temporarily"],synonyms:["fill in"]},
      {name:"stand out",description:["be noticable"]},
      {name:"stand up for",description:["support; defend"]},
      {name:"stand up to",description:["stay in good condition","resist"]},
      {name:"be taken aback",description:["be strongly surprised"]},
      {name:"take back",description:["admit that one was wrong in what one said"],synonyms:["back down"]},
      {name:"take down",description:["lengthen a garment"," seperate into pieces in order to repair or remove"," write down"],synonyms:["put down","let down"]},
      {name:"take on",description:["undertake responsibility","employ"]},
      {name:"take to",description:["like"]},
      {name:"turn away",description:["refuse to let in","refuse to help"]},
      {name:"turn in",description:["go to bed"]},
      {name:"turn out",description:["prove to be in the end","force sb to leave","produce"],synonyms:["bring out","put on"]},
      {name:"turn to",description:["go to sb for help, advice etc"]},
      {name:"work up",description:["to make yourself or another person feel upset or feel strong emotions","to bring something into existence, esp. gradually or in stages","to develop an idea, a plan, etc. by considering all the details:"]},
      {name:"lay out",description:["plan/arrange smth how it should appear"]},
      {name:"settle into",description:["become used to"]},
      {name:"rule out",description:["exclude smth as a possibility"]},
      {name:"trigger off",description:["cause series of events"],synonyms:["set off"]},
      {name:"inch along",description:["move or make progress very slowly"]},
      {name:"throw oneself at",description:["be ready to do anything for somebody"]},
      {name:"build on",description:["add to smth (like develop idea)"]},
      {name:"quiet down",description:["polite request to shut up"]},
      {name:"grow on",description:["gradually start to like someone/something"]},
      {name:"turn to",description:["go to somebody for help"]},
      {name:"spit out",description:["to tell unpleasant truth (something in the middle)"]},
      {name:"gang up on",description:["group against 1 person"]},
      {name:"string along",description:["deceive somebody for a long time about you are really intending to do"]},
      {name:"pull one over on",description:["make a practical joke"]},
      {name:"tell on",description:["snitch"]},
      {name:"whip out",description:["take out very quicky object in the middle"]},
      {name:"die down",description:["become quiet","stop some action"]},
      {name:"die down",description:["becone quiet","stop an action"]},
      {name:"speak to",description:["one quility relates to another","some information gives sign about something"]},
      {name:"frow on",description:["have a bad opinion about something"]},
      {name:"know of",description:["know but not personally"]},
      {name:"work at",description:["improve somethong"],synonyms:["work on"]},
      {name:"lay into",description:["to say bad things about somebody"]},
      {name:"jack up",description:["raise prices"]},
      {name:"square off against",description:["to prepare to fight, compete, or argue with someone"]},
      {name:"pan out",description:["to make a final result"]},
      {name:"but out",description:["to acquire a final share of something object in the middle"]},
      {name:"bounce back",description:["to recover from difficult situation"]},
      {name:"get ahead of oneself",description:["be hasty"]},
      {name:"read into",description:["seek for subtle meaning"]},
      {name:"go up against",description:["challenge someone or something"]}
    ]
  },
  idioms:{
    name:"idioms",
    picture404:"https://static.boredpanda.com/blog/wp-content/uploads/2015/06/English-Idioms-and-their-Meanings5__880.png",
    contents:[
      {name:"as right as rain",description:["very,very good"]},
      {name:"a blessing in disguise",description:["something good that is not recognized at first"]},
      {name:"a dime a dozen",description:["anything common and easy to get"]},
      {name:"a doubting Thomas",description:["sceptic, who needs evidence"]},
      {name:"a drop in the bucket",description:["a very small part"]},
      {name:"all bark and no bite",description:["when threatening without engaging in conflict"]},
      {name:"a taste of your own medicine",description:["when mistreated as you mistreat"]},
      {name:"apple of ones eye",description:["someone who is cherished above all others"]},
      {name:"an axe to grind",description:["to have dispute with someone"]},
      {name:"at the drop of a hat",description:["do smth imediatly"]},
      {name:"buy a lemon",description:["to buy a car that constantly gives problemd"]},
      {name:"two wrong do not make right",description:["unfortune events happen at the same time"]},
      {name:"birds of feather flock together",description:["similiar beings tend to group"]},
      {name:"the squeky wheel gets the greese",description:["the attention is paid to the noticable problems"]},
      {name:"far be it from me",description:["person is not right person to say but they want to say"]},
      {name:"under weather",description:["feel unwell"]},
      {name:"a foot in the door",description:["successful start"]},
      {name:"a different kettle of fish",description:["another case"]},
      {name:"chew the fat",description:["chat in leisurely way"]},
      {name:"in the black",description:["not in debt"]},
      {name:"hit the roof",description:["become extremely angry"]},
      {name:"get oneself worked up",description:["feel angry/upset about smth"]},
      {name:"by and large",description:["all considered together"]},      
    ],
  },
  prepositions:{
    name:"prepositions",
    contents:[
      {name:"good at",description:["good __ (proficiency)"]},
    ]
  }
}

export default ddata;
